### ISSUE TITLE
Module has not been updated to fix deprecated bash_task_helper/files/task_helper.sh

### ISSUE THREAD

**Issue by kjr2264** [puppetlabs/support-tasks#155]
#

task-succeed() {
  task-output "status" "success"
  _task_exit_string="$1"
  task-exit 0

}

# DEPRECATED

success() {
  task-output "_deprecation_warning" "WARN: bash_task_helper: use of success() is deprecated. Please use task-succeed() instead."
  task-succeed "$@"

}

**Comment by elainemccloskey** [comment]
Thanks for raising this issue and bringing this to our attention. We have now resolved this in the following PR:
https://github.com/puppetlabs/support-tasks/pull/162
