### ISSUE TITLE
Executing support_tasks::st0362_download_latest_pe_in_stream can lead to `Not a Supported primary server OS` if facter output is not exact

### ISSUE THREAD

**Issue by jordi-garcia** [puppetlabs/support-tasks#160]
## Describe the Bug
When executing `facter -p os.family` if facter returns more than `os.family`, the family variable (e.g. https://github.com/puppetlabs/support-tasks/blob/main/tasks/st0362_download_latest_pe_in_stream.sh#L8) won't contain the relevant value for case statement (e.g. https://github.com/puppetlabs/support-tasks/blob/main/tasks/st0362_download_latest_pe_in_stream.sh#L28-L42) and will exit the case statement via the default path displaying `Not a Supported primary server OS.` 

## Expected Behavior
Additional output for `facter -p os.family` shouldn't interfere in the close list OS selection for a case statement (e.g. https://github.com/puppetlabs/support-tasks/blob/main/tasks/st0362_download_latest_pe_in_stream.sh#L28-L42)

## Steps to Reproduce
1. Create a facter that outputs some text:

```
    Facter.add('outputmessage') do
    
        confine :kernel => 'Linux'
            puts "output something on the screen"
    end
```
2. Execute `facter -p os.family` on the terminal shell and the output will be: `output something on the screen RedHat` when the expected output should be just `RedHat`

## Environment
 - Version [e.g. 4.1.0]
 - Platform [e.g. CentOS 7]

## Potential Suggestion

Update any facter call with `| tail -1`

e.g.
1. Update https://github.com/puppetlabs/support-tasks/blob/main/tasks/st0362_download_latest_pe_in_stream.sh#L8:

`family=$(facter -p os.family | tail -1)`

2. Update https://github.com/puppetlabs/support-tasks/blob/main/tasks/st0362_download_latest_pe_in_stream.sh#L9:

`pe=$(facter -p pe_server_version | tail -1)`

3. Update https://github.com/puppetlabs/support-tasks/blob/main/tasks/st0362_download_latest_pe_in_stream.sh#L48:

`tarball_name="puppet-enterprise-$latest-$curlfam-$(facter -p os.release.major | tail -1)-$(facter -p os.architecture | tail -1).tar.gz"`

4. Update https://github.com/puppetlabs/support-tasks/blob/main/tasks/st0362_download_latest_pe_in_stream.sh#L50:

`echo "Downloading PE $latest $curlfam $(facter -p os.release.major | tail -1) $(facter -p os.architecture | tail -1)  to: $dllocation/${tarball_name}"`

5. Update https://github.com/puppetlabs/support-tasks/blob/main/tasks/st0362_download_latest_pe_in_stream.sh#L56:

`  "https://pm.puppetlabs.com/puppet-enterprise/$latest/puppet-enterprise-$latest-$curlfam-$(facter -p os.release.major | tail -1)-$(facter -p os.architecture | tail -1).tar.gz"`

**Comment by m0dular** [comment]
The example fact is invalid because it's lacking a [setcode do block](https://www.puppet.com/docs/puppet/6/custom_facts.html#two_parts_of_every_fact).  The issue is that this has broken `facter`, not that we're calling it incorrectly.  Also, text processing tools like `tail` should not be used to process json output since they simply split records on delimiters like newlines.
