### ISSUE TITLE
st0373_api_calls.sh: The ``create_role_cd4pe`` needs updated to be in line up with version 4 CD4PE

### ISSUE THREAD

**Issue by gavindidrichsen** [puppetlabs/support-tasks#163]
## Describe the Bug

The ``st0373_api_calls.create_role_cd4pe()`` creates a version 3 not a version 4 CD4PE role

## Expected Behavior

Should create the version 4 CD4PE role but instead it creates a version 3 one

## Additional Context

The code here <https://github.com/puppetlabs/support-tasks/blob/main/tasks/st0373_api_calls.sh#L18> needs to be adjusted to include all the permissions defined for version 4 <https://www.puppet.com/docs/continuous-delivery/4.x/integrate_with_puppet_enterprise.html#cd_pe_user_role>

**Comment by MartyEwings** [comment]
Deprecated this task see module readme for more
