### ISSUE TITLE
node purge checks strings that vary by version when setting result code

### ISSUE THREAD

**Issue by tkishel** [puppetlabs/support-tasks#42]
@m0dular 

https://github.com/puppetlabs/support-tasks/blob/master/tasks/kb0317b_purge_node.rb

```
exit(results.values.all? { |v| v[:result] == 'Certificate removed' }) ? 0 : 1
```

In PE 2019, its `Revoked certificate`:

```
[root@pe-201901-master~]# puppet node purge pe-201901-agent.puppetdebug.vlan 
WARN: Unresolved specs during Gem::Specification.reset:
      facter (< 4, >= 2.0.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Notice: Revoked certificate for pe-201901-agent.puppetdebug.vlan
Notice: Cleaned files related to pe-201901-agent.puppetdebug.vlan
Node "pe-201901-agent-ha.puppetdebug.vlan" was purged.
```

```
[root@pe-201901-replica~]# puppet task run support_tasks::kb0317b_purge_node agent_certnames="pe-201901-agent.puppetdebug.vlan" --nodes pe-201901-master.puppetdebug.vlan
Starting job ...
Note: The task will run only on permitted nodes.
New job ID: 6
Nodes: 1

Started on pe-201901-master.puppetdebug.vlan ...
Failed on pe-201901-master.puppetdebug.vlan
  Error: Task finished with exit-code 1
  pe-201901-agent.puppetdebug.vlan : 
    result : Node purged

Job failed. 1 node failed, 0 nodes skipped, 0 nodes succeeded.
Duration: 4 sec
```

**Comment by m0dular** [comment]
Ah, I see, thanks.  I'll put up a PR.

**Comment by m0dular** [comment]
So this is actually a dumb copy pasta mistake on my part.  I'm setting the result with

```
results[agent][:result] = output[:exit_code].zero? ? 'Node purged' : output
```

But then checking for the wrong string

```
results.values.all? { |v| v[:result] == 'Certificate removed' }
```

The result is clearly `Node purged`

```
$ bolt task run support_tasks::kb0317b_purge_node --nodes localhost agent_certnames=pe-201901-agent.platform9.puppet.net
Started on localhost...
Failed on localhost:
  The task failed with exit code 1
  {
    "pe-201901-agent.platform9.puppet.net": {
      "result": "Node purged"
    }
  }
Failed on 1 node: localhost
Ran on 1 node in 3.35 seconds
```

**Comment by m0dular** [comment]
@tkishel Fixed in https://github.com/puppetlabs/support-tasks/pull/44

**Comment by natemccurdy** [comment]
@m0dular Can you help me understand the scope of this change and when it's needed (i.e. which versions of PE).

If this is a valid fix, I'd like to port it upstream to my original project: [nate/purge_node](https://forge.puppet.com/nate/purge_node)

**Comment by m0dular** [comment]
@natemccurdy Sure!  We're looping over each agent we want to purge, and putting the result in an array like this:

```
results[agent][:result] = output[:exit_code].zero? ? 'Node purged' : output
```

Which makes the result `Node purged` on success, or the output of the command on failure.  The `exit` statement is trying to exit 0 if every result matches `Node purged` i.e. everything was successful, but via a copy paste error it's checking for `Certificate removed` instead.  What ends up happening is that it returns failure when it actually purged everything ok.  We should commit this upstream to avoid that confusion.
