### ISSUE TITLE
"puppet task show support_tasks" does not

### ISSUE THREAD

**Issue by linuxdan** [puppetlabs/support-tasks#71]
## Describe the Change You Would Like
Under "Getting Help" it says:
> To display help for the support_tasks task, run `puppet task show support_tasks`

That command returns nothing under PE 2019.2

I used `puppet task show --all` and got a list of all the tasks, including the ones from this module
Example:
> support_tasks::kb0009_Change_PE_Service_Loglevel

According to `puppet task show --help`, it is either all or a specific task, nothing about displaying tasks from one module.

Suggestion: `puppet task show --all | grep support_tasks`

**Comment by MartyEwings** [comment]
Thanks this will be addressed in the next release, which will be shortly

**Comment by MartyEwings** [comment]
Fixed in 1.1.1

**Comment by linuxdan** [comment]
Thanks
