### ISSUE TITLE
Puppet.conf server_list value not updated running st0263_rename_pe_master.sh

### ISSUE THREAD

**Issue by stolkie78** [puppetlabs/support-tasks#86]
## Describe the Bug
Running st0263_rename_pe_master.sh the end result is a broken configuration on the puppet master.
After starting up a new host with a new name the script will be run te reconfigure the PE stack.
Since 2019.8.3 the puppet.conf has and error. The server_list =  parameter is not updated.
After checking the Puppetinfra structure settings from the console it seems these values a not updated by the script.

puppet_enterprise::profile::agent::master_uris
puppet_enterprise::profile::agent::pcp_broker_list
puppet_enterprise::profile::agent::server_list

The result is that the first puppet agent -t succeeds on the Puppet Master, and the second one fails because the server_list settings is set incorrectly in the puppet.cof.

## Expected Behavior
A fully renamed working PE environment. With the correct puppet.conf setting

## Steps to Reproduce
1. Install Puppet Enterprise on machine and support_task module
2. Rename machine 
3. Run st0263_rename_pe_master.sh
4. puppet agent -t twice

## Environment
 - Version Puppet Enterprise 2019.8.3
 - Platform Centos 7

**Comment by elainemccloskey** [comment]
Thanks for raising this issue. After investigating this task further the decision was made to remove it as it was not functioning as expected. If anyone needs to rename their primary server they can follow this KB article:
https://support.puppet.com/hc/en-us/articles/360003489634-Change-the-hostname-of-a-primary-server-in-Puppet-Enterprise
