### ISSUE TITLE
st0307_generate_token

### ISSUE THREAD

**Issue by coreymbe** [puppetlabs/support-tasks#92]
## Describe the Bug
While this task is named correctly in the repo 'tasks/st0370_generate_token'; there is a typo in the forge bundle and the task is named 'st0307_generate_token'.

## Steps to Reproduce

puppet task run support_tasks::st0370_generate_token user=<USER> password=<PASSWORD> -n $(hostname -f)

Starting job ...
Failed to submit job: puppetlabs.orchestrator/invalid-task: No source besides task metadata was found in directory /etc/puppetlabs/code/environments/production/modules/support_tasks/tasks for task support_tasks::st0370_generate_token

**Comment by MartyEwings** [comment]
https://github.com/puppetlabs/support-tasks/commit/14f31e243b10e891a363730f6178f2dcd3e947f9#diff-148d5e63d34e600eea3919106e5ef36fd764dbb8e76f7d0e430a0692f21cd153

Looks like this was fixed in this commit and not released
